name: Actualizar conteo de publicaciones por mes

# Definir cuándo se ejecutará la acción (cron expression para todos los días a las 12:00 UTC)

on:
  schedule:    
    - cron: '0 11 * * *'  # Todos los días a las 12:00 UTC
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'Manually Trigger'
        type: choice
        options:
          - Manually Trigger
          - Add new post
          - Debug          
  # push: # Siempre que se haga un push en la branch
  #   branches: [main]  

# Definir los jobs
jobs:
  run-python-script: # build
    runs-on: ubuntu-latest  # Usaremos una máquina con Ubuntu

    permissions:
      contents: write
      
    steps:
      # Paso 1: Checkout (obtener el código del repositorio)
      - name: Checkout repository
        uses: actions/checkout@v4

      # Paso 2: Configurar Node.js (versión estable más reciente)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'  # Usar la última versión estable (LTS)

      # Paso 3: Instalar dependencias del proyecto
      - name: Install dependencies
        run: |
          npm install

      # Paso 4: Ejecutar el script de conteo
      - name: Run countPostsByMonth script
        run: |
          node ./utils/countPostsByMonth.mjs

  
      # Paso 5: Commit y Push si el archivo fue modificado
      - name: Commit and Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add public/data/postsByMonth.json
          if git diff --cached --quiet; then
            echo "No changes to commit";
          else
            git commit -m "Updated postsByMonth.json"
            git push
          fi
        if: success()  # Solo hacer commit si el script se ejecuta correctamente
